name = "SeaPearl"
uuid = "c13076dc-bdcd-48ba-bc88-4b44c2587ab3"
authors = ["Ilan Coulon", "FÃ©lix Chalumeau", "Tom Marty", "Tom Sander", "Pierre Tessier"]
version = "0.3.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CUDAKernels = "72cfdca4-0801-4ab0-bf6a-d52aa10adc57"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
GeometricFlux = "7e08b658-56d3-11e9-2997-919d5b31e4ea"
GraphSignals = "3ebe565e-a4b5-49c6-aed2-300248c3a9c1"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReinforcementLearning = "158674fc-8238-5cab-b5ba-03dfc80d1318"
RollingFunctions = "b0e4dd01-7b14-53d8-9b45-175a3e362653"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
CUDA = "2 - 3"
CUDAKernels = "0.1 - 0.3"
DataStructures = "0.18"
Distributions = "0.24 - 0.25"
FillArrays = "0.11 - 0.12"
Flux = "0.11 - 0.12"
GeometricFlux = "0.7.6"
GraphSignals = "0.1 - 0.2"
JuMP = "0.21"
KernelAbstractions = "0.6 - 0.7"
LightGraphs = "1.3"
MathOptInterface = "0.9"
NNlib = "0.7"
ProgressBars = "1"
ReinforcementLearning = "0.8 - 0.9"
RollingFunctions = "0.6"
SimpleWeightedGraphs = "1.1"
Zygote = "~0.5, 0.6"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
